#! /usr/bin/env node
const TG = require('../index');
const ARGS = process.argv; // TEST: ['-', '-', 'CMD']
let subcmd;


function done(err) {
	err && console.error('ERROR:', err);
	console.timeEnd('[Done]');
}


async function load(args) {
	var global = global || {};
	global.tgconfig = await TG.config();
	var cmd = (args[2] || '').replace(/-{2,}/g, '');
	var arg = [];
	for (let i = 3; i < args.length; i++)
		arg.push(args[i].trim().replace(/"/g, ''));

	//handle command generate
	if (cmd.indexOf(':') > -1) {

		let split = cmd.split(':');
		if (split.length < 2) {
			console.error('Invalid command format. Use "command:subcommand"');
			return done();
		}
		cmd = split[0].trim();
		subcmd = split[1].trim();
	
		if (!cmd)
			cmd = 'help';
	} 

	console.log('* Total Gen: [' + cmd.capitalize() + ']');
	console.time('[Done]');
	const params = subcmd ? [subcmd, ...arg] : arg; 
	var fn = FUNC[cmd];
	fn && fn.apply(global, params);
}


FUNC.help = function() {
	console.log('init                                   	: Initialize Total Gen');
	console.log('generate                                   : Generate code templates');
	done();
};

FUNC.console = async function() {
	TG.console();
};


FUNC.generate = function() {
	let args = Array.from(arguments).slice(1);

	let prompt;

	if (args.includes('--prompt')) {
		let index = args.indexOf('--prompt');
		prompt = args[index + 1];
	}


	if (args.includes('-p')) {
		let index = args.indexOf('-p');
		prompt = args[index + 1];
	}

	console.log(args);
	// handle sub help
	if (subcmd === 'help') {
		console.log('Usage: tg generate:<subcommand> [options]');
		console.log('Subcommands:');
		console.log('generate:resource               : Generate a resource template');
		console.log('generate:migration              : Generate a migration template');
		console.log('');
		console.log('Options:');
		console.log('--prompt "Your prompt here"     :Enhance with AI using custom prompt');
		done();
		return;
	}
	if (!subcmd) {
		console.error('Please specify a subcommand for "generate".');
		return done();
	}

	
	switch (subcmd) {
		case 'controller':
			TG.generatecontroller(args);
			break;
			case 'migration':
				let migrationtype = 'table';
				if (args.includes('-t')) {
					let index = args.indexOf('-t');
					migrationtype = args[index + 1];
				}
				TG.createmigration(args, migrationtype, prompt);
			break;
		case 'schema':
			TG.generateschema(args, prompt);
			break;
		case 'plugin':
			TG.generateplugin(args, prompt);
			break;
		default:
			console.error('Unknown subcommand:', subcmd);
			break;
	}

	done();
}

FUNC.init = function() {
	console.log('Initializing Total Gen...');
	TG.tginit().then(() => {
		console.log('Total Gen initialized successfully.');
		done();
	}).catch(err => {
		console.error('Error initializing Total Gen:', err);
		done(err);
	});
};

FUNC.migrate = async function() {
	await TG.migrate();
};

FUNC.migration = async function() {
	let args = Array.from(arguments).slice(1);
	// handle sub help
	if (subcmd === 'help') {
		console.log('Usage: tg migration:<subcommand> [options]');
		console.log('Subcommands:');
		console.log('migration:migrate   : Run migration operation');
		console.log('migration:rollback   : Revert all migrations');
		done();
		return;
	}
	if (!subcmd) {
		console.error('Please specify a subcommand for "migration".');
		return done();
	}

	switch (subcmd) {
		case 'rollback':
			await TG.rollback(args);
			done();
			break;
		case 'migrate':
			await TG.migrate(args);
			done();
			break;
		default:
			console.error('Unknown subcommand:', subcmd);
			break;
	}

}

FUNC.test = function() {
	require('../test.js');
	done();
};

FUNC.rollback

setTimeout(load, 10, ARGS);
